# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac924dd99338e1d3c1ccc28e5a781a08966a758f4f696319c20f03d69389b186082e34ed92145ab8d1f51a833267b03905ae2c2f119ef8a09529cd48fb1a8998

test:
  secret_key_base: 042826eacf57ad4be86b69e6588c792b89f781b1fd247d87b060bfcf24dd0e5c6139a9784698cdbeebb0873da6607764161b3b5dc3cbaf9d745c1e2b5f881681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
